title = "Smart[Fleet] Platform"
theme = "hugo-theme-learn"
[params]
  themeVariant = "custom"
  newsletterUrl = "http://vmsmartfleet.com:3030/api/Newsletters/"
  devportalUrl = "http://vmsmartfleet.com:9080/"
  isNewsletterUse = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]