title = "Smart[Fleet] Platform"
theme = "hugo-theme-learn"
[params]
  themeVariant = "custom"
  newsletterUrl = "https://smartfleet.sktelecom.com/api/Newsletters/"
  devportalUrl = "https://smartfleet.sktelecom.com:80/"
  isNewsletterUse = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]
